### ISSUE TITLE
Compatibility with "esc_pos_printer" package

### ISSUE THREAD

**Issue by ahmetakil** [marcusfelix/esc-pos-printer-flutter#12]
So this plugin works really well for usb connections but i want to use the Ticket structure in esc_pos_utils package (https://github.com/andrey-ushakov/esc_pos_utils).
I used the testTicket that is in the readme of the plugin and i did the following:

  `
final ticket = await testTicket();
await Escposprinter.printRawData(base64Encode(ticket.bytes));
`

which threw the exception: 

`
E/AndroidRuntime(27173): FATAL EXCEPTION: Thread-8
E/AndroidRuntime(27173): Process: <Flutter project name>, PID: 27173
E/AndroidRuntime(27173): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
E/AndroidRuntime(27173): 	at android.util.Base64.decode(Base64.java:119)
E/AndroidRuntime(27173): 	at br.com.samhaus.escposprinter.adapter.USBPrinterAdapter$3.run(USBPrinterAdapter.java:192)
`

Plugin works for simple .printText() operations so i assume it is configured correctly.

Am I doing something wrong or is there a bug here?
Thanks.

**Comment by irufano** [comment]
have you solved this problem? can you share?
